TLDR: she continues lying, now living by selling her "knowledge" to poor teachers, not knowing much more in education than she does in CS. Lying to tax payers and everybody around her. A new face appears.

note: things marked by (?) are marked after somebody pointed out they are weird. please
consider helping me improve those.

(credits in another place)

* The return of EGG

** Galili took a heavy blow for her lecture given in the 2013 ISOC conference. Since then she's Nav Gal, but she continues gluing new feathers to herself. Now she's training teachers in a workshop by the Tel Aviv University.

At the end of 2013 EGG made some drama around her. A lecture named "Deep Web Informatics"
that she gave in the ISOC conference, say proffesionals, suffers from "bold errors" in
the best case and "bullshit" at the worst case. The lecture was removed soon after from the
ISOC website after "the pipe" (tv show) and "room 404" (digital life blog) criticized her.

At the second half of 2014 EGG filed a defamation suit against 26 people including the ones
behind "the pipe" and "room 404" and other responders about the conference. The net reacted
by starting an online funding campaign for the defendants. The legal process is still
ongoing. The net is overloaded with publications and reactions about that affair (?) and
the surrounding context. Easy to find.

EGG changed her name and now she's Nav Gal. With her new name she's showing up quite a lot
online, without a mention of her past of course, and boasts an interesting and important 
job - Academic Director and lecturer in TA University. Although Gal teaches in a program 
for certificate studies (?) and not an academic degree, she's still training teachers. this
happens in the "academic center for personal and professional development for education and
society"(?) of the Education School(?). one of her courses is called "hibrid learning- in
practice (advanced online digital makers course)". That course is 30 hours long and gives
proficiency to Israel's teachers, increasing their income.

On 22/6 Nav referred to that course on her facebook page, calling it "unique and the first
- of - its - kind" and said it would start at the 5th of July. After a short while that
surprising post was removed. TA University confirmed that the course is two weeks long and
is indeed given right now. Moreover the University replied that they did not know about
her history, or her previous name, but they were impressed by her CV.

I talked to EGG last week. The conversation ended in a slam on her side, but even before
that she explained that her training on that subject was given to her in a course for
teachers given to her in the "Apple association" that is working on bridging the digital
gaps and technological accessibility. Online she presents herself as having much more
impressive CV. For example on the website of "Bar Orian Company" started by Anat Klomel,
Gal is presented as having the degree "Senior Lecturer in knowledge development". in
addition this is written about her: "Doctoral student in the field of strategy.
Researcher and facilitator in strategic consulting, online marketing, director of
training at the Ministry of Education in the field of ICT technologies and Project Based
Learning, network information manipulation and education technology, advisor for
corporations, companies and institutions about smart (web) surfing, information managenet
and social engineering. Owner of Masters degree in diplomacy and foreign policy from the
Hebrew University".

Poking inline raises a few more questions. Unlike her presentation on the "Bar Orian
Company",  in the company "...(dont wanna translate the name)(?)..." she's presented as
"finishing a PhD in Learning Systems". Here, too, it doesnt say where she's studying.
From that company's website (whose phone number, btw, is the Gal's number) you get the
impression of a thriving company, with many schools as clients, ie, Gal is probably a
third party provider for the ministy of education, and not its direct worker. I contacted
ministry of education and asked if Gal is indeed the director of mentorship(?) in the
Technology and ICT, the answer was simple: "after checking the DB, no such name was found"


My direct question about the Doctoral Studying(?) and the subject wasn't answered. Gal
does indeed have a Master's degree, but again that's a bit axaggerated- she has a non 
exploratory (?) diploma in international relations and national security research and
diplomacy from the Hebrew University. The relation with the Apple association is true.
From the association we gathered that she worked there in the years 2014-2016 as a
mentor pedagog for embedding innovation in schools, after presenting CV that "Met the
profile requirements of the job and present rich experience and appropriate education in
the worlds of education and technology. Nev has worked in a number of schools across the
country and in most of them has received excellent feedback and has managed to lead to a
fundamental change in the perception of teaching both among teachers and principals. In
a small number of schools, gaps and conflicts arose and it seemed that there were
shortcomings in communication and complex conduct on the part of Nev. In these cases we
replaced her with another pedagogical facilitator from the staff"

checking Gal's recent history the name of Anat Klumel shows up again and again. She
herself didn't agree to an interview, saying that "Gal does an excelent job". In a post
from Dec 2012, a year prior to the famous lecture in ISOC, she wrote about an excelent 
collaboration between the two including "similar experience in academia" and an essay in
a professional magazin. Another interesting about their connection was presented this
month by Klumel in the website "(some name)": "Me and Nav Gal wrote an article about
managing a campaign for local elections... this collaboration began when Nav Gal managed
a few campaigns for candidates for the 2013 local elections". Published in 2017 in
(some magazine) was an article that presented Gal as the (some boring part).

TA Uni's reply- "the mentor in question works in presenting workshops for education that
are not part of the Academic programs. She has much experience as a mentor for teachers
in schools all around the country (blah blah) and this has nothing to do with the (whole
ISOC drama) subject".


Nav Gal slammed the phone and answered nothning. Anat Klumel refused to answer.

